### ISSUE TITLE
VAProgressCircle Doesn't Working As Expected

### ISSUE THREAD

**Issue by afiq90** [MitchellMalleo/VAProgressCircle#2] opened 2015-12-10 07:11 UTC
Hey guys, I had  a problem with a progress circle. I'm using this library to download video online. My problem is numberLabel in VAProgressCircle doesn't tele with my download progress status. Let say my download problem is 45% but numberLabel goes up to 100. For better understanding I attached the video and code below : 

https://youtu.be/SRA8c10JtV8
http://pastebin.com/eVC4PMDU

thank you for this great library.

**Comment by MitchellMalleo** [comment] 2015-12-10 15:37
Hey afiq90,

Thanks for the kind words. I took a look at your video and your code and it looks like there wasn't enough checking in the UIProgressLabel and the VAProgressCircle for erroneous values. I also could not use the VideoDownloadHelper you were using, so I tested using a different downloader. I've pushed a fix that has more error checking for the setProgress and the countToNumber methods, so feel free to checkout the new repository and let me know if the issue is fixed. If not, we can continue from there.

**Comment by afiq90** [comment] 2015-12-11 08:12
Thank you for responding, and if you're curios this is my method that I'm using for downloading a video using AFNetworking :  

VideoDownloadHelper.m
https://gist.github.com/afiq90/bd104a97b15f0d1a0a59

Also, I can't wait to try your new update once I get home.

**Closed as completed** 2015-12-14 19:39 UTC
